name: Run Snake Game

on:
  push:
    branches:
      - main

jobs:
  run-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Snake Game
        run: python snake.py
